name: Python

on:
  push:
    branches: [ master ]  
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Flake8 linting
      run: |
        flake8 2020/. --exclude=venv/,2019/ --count --select=E9,F63,F7,F82 --ignore=E203,402 --show-source --statistics
        flake8 2020/. --exclude=venv/,2019/ --count --exit-zero --max-complexity=10 --ignore=E203,E402 --statistics
    - name: Black code format
      run: |
        black . --exclude=2019 --check --line-length 79
    - name: Python unit tests
      run: |
        pytest 2020/**/python/*.py