name: Python

on:
  push:
    branches:
      - master
    paths:
      - '**/*.py'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip setuptools wheel
        pip3 install -r requirements.txt
    - name: Flake8 linting
      run: ./tools/check_pylint.sh
    - name: Black code format
      run: ./tools/check_python_format.sh
    - name: Python unit tests
      run: python3 -m pytest year*/*/solutions.py

